export const STAR_WARS_ICONS = {
    '1626636_yoda_master_star wars_puppet_jedi.png': require('@/assets/images/icons/1626636_yoda_master_star wars_puppet_jedi.png'),
    '1626635_star wars_tatooine_tusken_raider.png': require('@/assets/images/icons/1626635_star wars_tatooine_tusken_raider.png'),
    '1626631_gon_jinn_qui_jedi_star wars.png': require('@/assets/images/icons/1626631_gon_jinn_qui_jedi_star wars.png'),
    '1626632_rebel_robot_droid_star wars_r2d2.png': require('@/assets/images/icons/1626632_rebel_robot_droid_star wars_r2d2.png'),
    '1626633_rebel_pilot_helmet_red_star wars_rebel_pilot_five_red_star wars_helmet.png': require('@/assets/images/icons/1626633_rebel_pilot_helmet_red_star wars_rebel_pilot_five_red_star wars_helmet.png'),
    '1626634_stormtrooper_star wars_empire.png': require('@/assets/images/icons/1626634_stormtrooper_star wars_empire.png'),
    '1626629_jedi_kenobi_star wars_obiwan.png': require('@/assets/images/icons/1626629_jedi_kenobi_star wars_obiwan.png'),
    '1626630_princess_leia_rebel_star wars.png': require('@/assets/images/icons/1626630_princess_leia_rebel_star wars.png'),
    '1626626_lightsaber_weapon_jedi_star wars_rotj_luke.png': require('@/assets/images/icons/1626626_lightsaber_weapon_jedi_star wars_rotj_luke.png'),
    '1626627_star wars_lobot.png': require('@/assets/images/icons/1626627_star wars_lobot.png'),
    '1626628_skywalker_jedi_luke_star wars.png': require('@/assets/images/icons/1626628_skywalker_jedi_luke_star wars.png'),
    '1626624_weapon_lightsaber_darth_star wars_vader_sith.png': require('@/assets/images/icons/1626624_weapon_lightsaber_darth_star wars_vader_sith.png'),
    '1626625_luke_lightsaber_anh_star wars_weapon_skywalker_jedi.png': require('@/assets/images/icons/1626625_luke_lightsaber_anh_star wars_weapon_skywalker_jedi.png'),
    '1626621_helmet_star wars_fett_helmet_mandalorian_clone_jango_star wars_mandalorian_fett_jango_clone.png': require('@/assets/images/icons/1626621_helmet_star wars_fett_helmet_mandalorian_clone_jango_star wars_mandalorian_fett_jango_clone.png'),
    '1626622_star wars_jawa.png': require('@/assets/images/icons/1626622_star wars_jawa.png'),
    '1626623_rebel_lando_calrissian_star wars.png': require('@/assets/images/icons/1626623_rebel_lando_calrissian_star wars.png'),
    '1626619_han_star wars_rebel_solo.png': require('@/assets/images/icons/1626619_han_star wars_rebel_solo.png'),
    '1626620_jabba_the_star wars_hutt.png': require('@/assets/images/icons/1626620_jabba_the_star wars_hutt.png'),
    '1626617_ewok_wicket_endor_star wars.png': require('@/assets/images/icons/1626617_ewok_wicket_endor_star wars.png'),
    '1626618_han shot first_greedo_star wars.png': require('@/assets/images/icons/1626618_han shot first_greedo_star wars.png'),
    '1626614_maul_star wars_sith_darth.png': require('@/assets/images/icons/1626614_maul_star wars_sith_darth.png'),
    '1626615_jedi_star wars_sith_darth_vader_anakin_skywalker.png': require('@/assets/images/icons/1626615_jedi_star wars_sith_darth_vader_anakin_skywalker.png'),
    '1626616_sidious_palpatine_emperor_sith_star wars_empire_darth.png': require('@/assets/images/icons/1626616_sidious_palpatine_emperor_sith_star wars_empire_darth.png'),
    '1626612_star wars_chewbacca_wookie_chewie_rebel.png': require('@/assets/images/icons/1626612_star wars_chewbacca_wookie_chewie_rebel.png'),
    '1626613_clone_star wars_trooper_empire.png': require('@/assets/images/icons/1626613_clone_star wars_trooper_empire.png'),
    '1626611_droid_robot_protocol_star wars_c3p0.png': require('@/assets/images/icons/1626611_droid_robot_protocol_star wars_c3p0.png'),
    '1626609_rebel_mon calamari_star wars_admiral_ackbar.png': require('@/assets/images/icons/1626609_rebel_mon calamari_star wars_admiral_ackbar.png'),
    '1626610_boba_mandalorian_hunter_bounty_star wars_boba_fett_bounty_star wars_mandalorian_hunter_fett.png': require('@/assets/images/icons/1626610_boba_mandalorian_hunter_bounty_star wars_boba_fett_bounty_star wars_mandalorian_hunter_fett.png'),
  }